### PR TITLE
feat: toggle recording on/off

### PR DESCRIPTION
**Pull request by gimKondo**
toggle recording status on/off

### CODE REVIEW

**Comment by cahlchang** [comment]
Thank you very much!
This function was really necessary.

As an operation, is it assumed that the on / off of the toggle is checked by looking at the tab of chrome?

**Comment by gimKondo** [comment]
Yes, I checked at just only chrome.
I didn't find it, but are there possibly any problems on another platform?

**Comment by gimKondo** [comment]
P.S. You can check this feature here. I hope this is useful for you.

https://gimkondo.github.io/talkw2/index.html

**Comment by cahlchang** [comment]
I see!
This is very easy to understand, it looks like a nice idea.
I tried incorporating it immediately.
Thank you for PR!

**Pull request merged**
